### ISSUE TITLE
Failed to fetch GPG key

### ISSUE THREAD

**Issue by stevenscg** [threatstack/threatstack-ansible#36]
Latest version of this role on an RHEL7/CentOS7 installation fails with this:

```
TASK [threatstack : Add ThreatStack repo GPG key.] *************************************************
fatal: [10.101.20.94]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch key at https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK , error was: HTTP Error 403: Forbidden"}
```

I can download the key file shown at the URL above, but obviously have to be logged into my account to do so.

#### Workaround

Download the key while logged in, add it to the role in a `files` directory, update the task to upload the file and then install it.

For yum-based systems:
```
- name: Upload ThreatStack repo GPG key
  copy:
    src: RPM-GPG-KEY-THREATSTACK
    dest: /etc/pki/rpm-gpg/

- name: Add ThreatStack repo GPG key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK
```
